// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: notes/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteService_Fetch_FullMethodName                                   = "/notes.v1.NoteService/Fetch"
	NoteService_Create_FullMethodName                                  = "/notes.v1.NoteService/Create"
	NoteService_CancelRegisterIdentityByInstructionLink_FullMethodName = "/notes.v1.NoteService/CancelRegisterIdentityByInstructionLink"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	Fetch(ctx context.Context, in *NoteFilter, opts ...grpc.CallOption) (*Notebook, error)
	Create(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Notebook, error)
	CancelRegisterIdentityByInstructionLink(ctx context.Context, in *MessagingIdentityRequest, opts ...grpc.CallOption) (*Notebook, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) Fetch(ctx context.Context, in *NoteFilter, opts ...grpc.CallOption) (*Notebook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notebook)
	err := c.cc.Invoke(ctx, NoteService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) Create(ctx context.Context, in *Note, opts ...grpc.CallOption) (*Notebook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notebook)
	err := c.cc.Invoke(ctx, NoteService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CancelRegisterIdentityByInstructionLink(ctx context.Context, in *MessagingIdentityRequest, opts ...grpc.CallOption) (*Notebook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notebook)
	err := c.cc.Invoke(ctx, NoteService_CancelRegisterIdentityByInstructionLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations should embed UnimplementedNoteServiceServer
// for forward compatibility.
type NoteServiceServer interface {
	Fetch(context.Context, *NoteFilter) (*Notebook, error)
	Create(context.Context, *Note) (*Notebook, error)
	CancelRegisterIdentityByInstructionLink(context.Context, *MessagingIdentityRequest) (*Notebook, error)
}

// UnimplementedNoteServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteServiceServer struct{}

func (UnimplementedNoteServiceServer) Fetch(context.Context, *NoteFilter) (*Notebook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedNoteServiceServer) Create(context.Context, *Note) (*Notebook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNoteServiceServer) CancelRegisterIdentityByInstructionLink(context.Context, *MessagingIdentityRequest) (*Notebook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRegisterIdentityByInstructionLink not implemented")
}
func (UnimplementedNoteServiceServer) testEmbeddedByValue() {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	// If the following call pancis, it indicates UnimplementedNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Fetch(ctx, req.(*NoteFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Create(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CancelRegisterIdentityByInstructionLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagingIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CancelRegisterIdentityByInstructionLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CancelRegisterIdentityByInstructionLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CancelRegisterIdentityByInstructionLink(ctx, req.(*MessagingIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.v1.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _NoteService_Fetch_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _NoteService_Create_Handler,
		},
		{
			MethodName: "CancelRegisterIdentityByInstructionLink",
			Handler:    _NoteService_CancelRegisterIdentityByInstructionLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notes/v1/api.proto",
}
